
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [1]:
import numpy as np

array= np.arange(10)
print(array)



ModuleNotFoundError: No module named 'numpy'

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [14]:
num_1d = np.array([1,2,3,4,5,6,7,8,9])
num_1d.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Access the element at the second row, second column.


In [5]:
num_1d[1]

NameError: name 'num_1d' is not defined

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [48]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 + array2)
print(array1 - array2)
print(array1 / array2)


[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [29]:
numbers = np.array([1,2,3,4,5])
print(numbers.mean())
print(numbers.std())
print(numbers.sum())

3.0
1.4142135623730951
15


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [30]:
numbers = np.array([1,2,3,4,5,6])
numbers.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [32]:
random_num = np.random.randint(0, 100, size=(5, 5))
print(random_num)

[[27 15  6  2 44]
 [97  5 90 83 14]
 [94 55 64 22 89]
 [50 96 75 43 13]
 [84 34  1 68 62]]


Replace all values in the sub-array with a specific value.


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [43]:
num_2d = np.random.randint(0,100, size=(3,3))
print(num_2d)

[[61 22 86]
 [55 41  7]
 [97 40 37]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [41]:


import numpy as np


array_2d = np.random.randint(0, 100, size=(3, 3))
array_1d = np.random.randint(0, 100, size=(3,1))

print("2D Array:")
print(array_2d)

print("\n1D Array:")
print(array_1d)


result = array_2d + array_1d

print("\nResulting Array after Broadcasting:")
print(result)


2D Array:
[[ 0 36  3]
 [37 34 53]
 [ 3 59 84]]

1D Array:
[[93]
 [72]
 [ 7]]

Resulting Array after Broadcasting:
[[ 93 129  96]
 [109 106 125]
 [ 10  66  91]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [35]:
array1 = np.random.randint(0, 100, size=(3, 3))
array2 = np.random.randint(0, 100, size=(3, 3))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)


Array 1:
[[47 22 67]
 [ 6 13 88]
 [77  5 16]]

Array 2:
[[89 94 13]
 [42 31 81]
 [ 2 50 47]]


In [36]:
horizontally_concatenated = np.hstack((array1, array2))
vertically_concatenated = np.vstack((array1, array2))

print("\nHorizontally Concatenated:")
print(horizontally_concatenated)

print("\nVertically Concatenated:")
print(vertically_concatenated)


Horizontally Concatenated:
[[47 22 67 89 94 13]
 [ 6 13 88 42 31 81]
 [77  5 16  2 50 47]]

Vertically Concatenated:
[[47 22 67]
 [ 6 13 88]
 [77  5 16]
 [89 94 13]
 [42 31 81]
 [ 2 50 47]]


In [ ]:
dont know

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [33]:
import numpy as np


array = [1, 2, 1, 2, 3, 4, 5, 6, 8, 9, 1, 2, 2, 22, 21, 1, 1, 1, 1, 2, 5]


count_dict = {}

for num in array:
    if num in count_dict:
        count_dict[num] += 1
    else:
        count_dict[num] = 1


mode = max(count_dict, key=count_dict.get)
mode_count = count_dict[mode]

print("Mode:", mode)
print("Count:", mode_count)


Mode: 1
Count: 7


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

